export const MONGO_DB_VARS = {
  MONGO_USER: 'MONGO_USER',
  MONGO_PASSWORD: 'MONGO_PASSWORD',
  MONGO_URL: 'MONGO_URL',
  MONGO_DB: 'MONGO_DB',
  SMTP_PORT: 'SMTP_PORT',
  SMTP_HOST: 'SMTP_HOST',
  SMTP_USERNAME: 'SMTP_USERNAME',
  SMTP_PASSWORD: 'SMTP_PASSWORD',
  SMTP_FROM: 'SMTP_FROM',
  JWT_SECRET: 'JWT_SECRET',
  FRONTEND_DOMAIN: 'FRONTEND_DOMAIN',
};

export const SORT_ORDER = {
  ASC: 'asc',
  DESC: 'desc',
};
